//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoAppRev1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.DynamicData;
    using System.ComponentModel.DataAnnotations;
    // IB needed to stop time showing up and use DisplayFormat

    public partial class Task
    {
        public int TaskID { get; set; }
        public int TaskListID { get; set; }
        public string TaskName { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Completed { get; set; }
    
        public virtual TaskList TaskList { get; set; }
    }
}
